packages:
  - clients/*
  - packs/*
  - sdk/typescript-client
  - sdk/typescript-hosted-contract
  - sdk/typescript-pack/packages/*
  - web/console
  - web/demos
  - web/manual
  - web/platform

onlyBuiltDependencies: []
