//! Deterministic, capability-denying host for portable Activity Pack Components.

mod error;
mod host;

pub use error::ComponentHostErrorV1;
pub use host::{
    CALLBACK_CONCURRENCY_LIMIT, CALLBACK_FUEL, COMPILE_CONCURRENCY_LIMIT,
    COMPONENT_MAX_INPUT_BYTES, COMPONENT_MAX_OUTPUT_BYTES, COMPONENT_MAX_WASM_STACK_BYTES,
    COMPONENT_PARALLEL_COMPILATION, ComponentPackHostV1, STORE_INSTANCE_LIMIT,
    STORE_LINEAR_MEMORY_BYTES, STORE_MEMORY_LIMIT, STORE_TABLE_ELEMENT_LIMIT, STORE_TABLE_LIMIT,
};
