import { spawn, spawnSync } from "node:child_process";
import { createHash, randomBytes } from "node:crypto";
import { once } from "node:events";
import { constants } from "node:fs";
import { lstat, mkdir, open, readFile, writeFile } from "node:fs/promises";
import { createServer } from "node:net";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const REPOSITORY_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const DEVELOPMENT_MODE = "visible-local-only";
const LISTING_DIGEST = "blake3:e3d401e783cec1ae4f911f682e8289054275dece60a0482b02f63e872f27dcc1";
const DEVELOPMENT_USER_ID = "00000000-0000-4000-8000-00000000d001";
const DEVELOPMENT_PROVIDER_SUBJECT = "worldstream-development";
const DEVELOPMENT_LOGIN = "worldstream-local-developer";
const SERVICE_AUTHORITY = "worldstream-local-service-authority-000000000000";
const CONTROLLER_AUTHORITY = "worldstream-local-controller-authority-000000000";
const HOST_INSTALLATION_ID = "hosted-dev";
const FAKE_OPENROUTER_KEY = "worldstream-development-key-000000000000";
const SUPABASE_EXCLUDES =
  "realtime,storage-api,imgproxy,mailpit,postgres-meta,studio,edge-runtime,logflare,vector,supavisor";
const READINESS_TIMEOUT_MS = 60_000;

export function hostedDevelopmentPorts(environment = process.env) {
  const ports = {
    runtime: port(environment.WORLDSTREAM_HOSTED_RUNTIME_PORT ?? "9410", "Runtime"),
    controller: port(environment.WORLDSTREAM_HOSTED_CONTROLLER_PORT ?? "9420", "Controller"),
    gateway: port(environment.WORLDSTREAM_HOSTED_GATEWAY_PORT ?? "8080", "Hosted Gateway"),
    product: port(environment.WORLDSTREAM_HOSTED_PRODUCT_PORT ?? "5180", "product"),
    heist: port(environment.WORLDSTREAM_HOSTED_HEIST_PORT ?? "5173", "Agent Heist"),
    platform: port(environment.WORLDSTREAM_HOSTED_PLATFORM_PORT ?? "3000", "Platform BFF"),
    fakeOpenRouter: port(
      environment.WORLDSTREAM_HOSTED_FAKE_OPENROUTER_PORT ?? "8787",
      "fake OpenRouter",
    ),
  };
  if (ports.controller !== 9420 || ports.heist !== 5173) {
    throw new Error(
      "Controller 9420 and Agent Heist 5173 are fixed by the reviewed local client declaration. " +
        "Regenerate and review that declaration before changing them.",
    );
  }
  if (new Set(Object.values(ports)).size !== Object.values(ports).length) {
    throw new Error("hosted development ports must be unique");
  }
  return ports;
}

export function assertHostedDevelopmentAllowed(environment = process.env) {
  if (environment.NODE_ENV === "production" || environment.VERCEL_ENV === "production") {
    throw new Error("hosted development substitutes are forbidden in production");
  }
}

export function renderHostedDevelopmentConfig({ dataDirectory, secretFile, runtimePort }) {
  return `# Generated by pnpm hosted:dev. Retained local data is not deleted on shutdown.
config_version = 1

[server]
bind = "127.0.0.1:${runtimePort}"

[storage]
profile = "sqlite-bundled"
data_dir = ${JSON.stringify(dataDirectory)}
deployment_lineage = "development/hosted-local"
storage_epoch = 1

[authority.bootstrap]
secret_file = ${JSON.stringify(secretFile)}
`;
}

async function main() {
  const checkOnly = parseArguments(process.argv.slice(2));
  assertHostedDevelopmentAllowed();
  const ports = hostedDevelopmentPorts();
  const stateRoot = join(REPOSITORY_ROOT, ".worldstream", "hosted-dev");
  // The retained kernel contract still names this sibling directory `studio`;
  // it contains Controller authority/state and does not start a Studio UI.
  const stateDirectory = join(stateRoot, "studio");
  const dataDirectory = join(stateRoot, "data");
  const secretFile = join(stateRoot, "authority.secret");
  const configFile = join(stateRoot, "worldstream.toml");
  const worldstreamctl = join(REPOSITORY_ROOT, "target", "debug", "worldstreamctl");
  const children = [];
  let ownsSupabase = false;
  let managedStarted = false;
  let worldstreamctlBuilt = false;
  let shuttingDown = false;

  const commonEnvironment = {
    ...process.env,
    NODE_ENV: "development",
    WORLDSTREAM_DEPLOYMENT_ENVIRONMENT: "development",
    WORLDSTREAM_HOSTED_INSTALLATION_ID: HOST_INSTALLATION_ID,
    WORLDSTREAM_HOSTED_CONTROLLER_AUTHORITY: CONTROLLER_AUTHORITY,
  };
  const ctl = (command, options = {}) =>
    run(
      worldstreamctl,
      [
        "--config",
        configFile,
        command[0],
        ...command.slice(1),
        "--state-dir",
        stateDirectory,
        "--controller",
        `127.0.0.1:${ports.controller}`,
        "--json",
      ],
      { ...options, environment: commonEnvironment },
    );

  try {
    preflight();
    await Promise.all([
      run("pnpm", ["install", "--frozen-lockfile"], { environment: commonEnvironment }),
      run(
        "cargo",
        [
          "build",
          "-p",
          "worldstream-server",
          "-p",
          "worldstream-studio-supervisor",
          "-p",
          "worldstream-hosted-gateway",
          "--bins",
        ],
        { environment: commonEnvironment },
      ),
    ]);
    worldstreamctlBuilt = true;
    await Promise.all([
      run("pnpm", ["--filter", "@worldstream/platform", "build"], {
        environment: commonEnvironment,
      }),
      run("pnpm", ["--filter", "@worldstream/pack-sdk", "build"], {
        environment: commonEnvironment,
      }),
    ]);

    await mkdir(stateRoot, { recursive: true, mode: 0o700 });
    await ensureSecret(secretFile);
    await writeFile(
      configFile,
      renderHostedDevelopmentConfig({ dataDirectory, secretFile, runtimePort: ports.runtime }),
      { mode: 0o600 },
    );

    ownsSupabase = !(await succeeds("supabase", ["status", "-o", "env"], commonEnvironment));
    if (ownsSupabase) {
      await run("supabase", ["start", "-x", SUPABASE_EXCLUDES], {
        environment: supabaseEnvironment(commonEnvironment),
      });
    }
    await run("supabase", ["migration", "up", "--local"], {
      environment: supabaseEnvironment(commonEnvironment),
    });
    const supabase = parseEnvironmentOutput(
      (
        await run("supabase", ["status", "-o", "env"], {
          capture: true,
          sensitive: true,
          environment: supabaseEnvironment(commonEnvironment),
        })
      ).stdout,
    );
    await seedSupabase(supabase, commonEnvironment);

    await ctl(["init"]);
    await ctl(["server", "stop"], { allowFailure: true, quiet: true });
    await ctl(["server", "controller-stop"], { allowFailure: true, quiet: true });
    const reuseHeist = await compatibleAgentHeistAlreadyRunning(ports.heist);
    if (reuseHeist) {
      process.stdout.write(
        `[Agent Heist] Reusing the compatible approved client already on port ${ports.heist}.\n`,
      );
    }
    await assertPortsAvailable(ports, reuseHeist ? new Set(["heist"]) : new Set());
    await importClientDeclarations(ctl);

    const heistOrigin = `http://127.0.0.1:${ports.heist}`;
    await ctl(["server", "start", "--participant-console-origin", heistOrigin]);
    managedStarted = true;

    const productOrigin = `http://127.0.0.1:${ports.product}`;
    const platformOrigin = `http://127.0.0.1:${ports.platform}`;
    const childEnvironment = {
      ...commonEnvironment,
      CANONICAL_ORIGIN: productOrigin,
      SUPABASE_URL: requiredSupabase(supabase, "API_URL"),
      SUPABASE_PUBLISHABLE_KEY:
        supabase.PUBLISHABLE_KEY ?? requiredSupabase(supabase, "ANON_KEY"),
      SUPABASE_DATA_SECRET_KEY:
        supabase.SECRET_KEY ?? requiredSupabase(supabase, "SERVICE_ROLE_KEY"),
      WORLDSTREAM_SESSION_KEY_BASE64: Buffer.alloc(32, 7).toString("base64"),
      WORLDSTREAM_OAUTH_KEY_BASE64: Buffer.alloc(32, 9).toString("base64"),
      WORLDSTREAM_PLATFORM_BIND: "127.0.0.1",
      WORLDSTREAM_PLATFORM_PORT: String(ports.platform),
      WORLDSTREAM_DEVELOPMENT_IDENTITY_BYPASS: DEVELOPMENT_MODE,
      WORLDSTREAM_DEVELOPMENT_AUTH_USER_ID: DEVELOPMENT_USER_ID,
      WORLDSTREAM_DEVELOPMENT_GITHUB_SUBJECT: DEVELOPMENT_PROVIDER_SUBJECT,
      WORLDSTREAM_DEVELOPMENT_GITHUB_LOGIN: DEVELOPMENT_LOGIN,
      WORLDSTREAM_DEVELOPMENT_FAKE_OPENROUTER: DEVELOPMENT_MODE,
      WORLDSTREAM_FAKE_OPENROUTER_BIND: "127.0.0.1",
      WORLDSTREAM_FAKE_OPENROUTER_PORT: String(ports.fakeOpenRouter),
      WORLDSTREAM_DEVELOPMENT_OPENROUTER_KEY: FAKE_OPENROUTER_KEY,
      WORLDSTREAM_LOCAL_PLATFORM_BFF_TARGET: platformOrigin,
      VITE_WORLDSTREAM_SUPERVISOR_URL: `http://127.0.0.1:${ports.controller}`,
    };

    children.push(
      startChild(
        "Platform BFF",
        "node",
        [join(REPOSITORY_ROOT, "web", "platform", "dist", "dev-server.js")],
        childEnvironment,
      ),
      startChild(
        "fake OpenRouter",
        "node",
        [join(REPOSITORY_ROOT, "scripts", "hosted-fake-openrouter.mjs")],
        childEnvironment,
      ),
      startChild(
        "product",
        "pnpm",
        [
          "--dir",
          "web/demos",
          "exec",
          "vite",
          "--host",
          "127.0.0.1",
          "--port",
          String(ports.product),
          "--strictPort",
        ],
        childEnvironment,
      ),
      startChild(
        "Hosted Gateway",
        join(REPOSITORY_ROOT, "target", "debug", "worldstream-hosted-gateway"),
        [],
        {
          ...childEnvironment,
          HOSTED_GATEWAY_BIND: `127.0.0.1:${ports.gateway}`,
          WORLDSTREAM_HOST_ADAPTER_UPSTREAM: `127.0.0.1:${ports.controller}`,
          WORLDSTREAM_RUNTIME_UPSTREAM: `127.0.0.1:${ports.runtime}`,
          WORLDSTREAM_HOSTED_CONTROLLER_AUTHORITY: CONTROLLER_AUTHORITY,
          WORLDSTREAM_HOSTED_CLIENT_ORIGIN: heistOrigin,
          WORLDSTREAM_PUBLIC_AUTHORITY: `127.0.0.1:${ports.gateway}`,
          WORLDSTREAM_VERCEL_SERVICE_AUTHORITY: SERVICE_AUTHORITY,
          WORLDSTREAM_LISTING_ALLOWLIST: LISTING_DIGEST,
          WORLDSTREAM_DEPLOYMENT_VERSION: "hosted-local-development",
          RUST_LOG: "worldstream_hosted_gateway=info",
        },
      ),
    );
    if (!reuseHeist) {
      children.push(
        startChild(
          "Agent Heist",
          "pnpm",
          [
            "--dir",
            "clients/agent-heist-web",
            "exec",
            "vite",
            "--host",
            "127.0.0.1",
            "--port",
            String(ports.heist),
            "--strictPort",
          ],
          childEnvironment,
        ),
      );
    }

    await readiness(ports, ctl, children);
    await verifyDevelopmentFlow(ports);
    printReady(ports, supabase);
    if (checkOnly) {
      process.stdout.write("Hosted local-development acceptance check passed.\n");
      return;
    }

    await waitUntilStopped(children, () => {
      shuttingDown = true;
    });
  } finally {
    shuttingDown = true;
    if (managedStarted && worldstreamctlBuilt) {
      await ctl(["server", "stop"], { allowFailure: true, quiet: true });
    }
    if (worldstreamctlBuilt) {
      await ctl(["server", "controller-stop"], { allowFailure: true, quiet: true });
    }
    await stopChildren(children);
    if (ownsSupabase) {
      await run("supabase", ["stop"], {
        allowFailure: true,
        quiet: true,
        environment: supabaseEnvironment(commonEnvironment),
      });
    }
  }

  function startChild(name, command, args, environment) {
    return ownedChild(name, command, args, environment, () => shuttingDown);
  }
}

function parseArguments(args) {
  if (args.length === 0) return false;
  if (args.length === 1 && args[0] === "--check") return true;
  throw new Error("usage: pnpm hosted:dev [--check]");
}

function preflight() {
  for (const command of ["cargo", "pnpm", "psql", "supabase"]) {
    const result = spawnSync(command, ["--version"], { cwd: REPOSITORY_ROOT, stdio: "ignore" });
    if (result.status !== 0) {
      throw new Error(`${command} is required; install it and retry pnpm hosted:dev`);
    }
  }
}

async function ensureSecret(path) {
  try {
    const stats = await lstat(path);
    if (!stats.isFile() || stats.isSymbolicLink() || stats.size !== 32 || (stats.mode & 0o077) !== 0) {
      throw new Error("hosted development authority secret must be a regular 32-byte mode-0600 file");
    }
  } catch (error) {
    if (!(error instanceof Error) || !("code" in error) || error.code !== "ENOENT") throw error;
    const handle = await open(path, constants.O_CREAT | constants.O_EXCL | constants.O_WRONLY, 0o600);
    try {
      await handle.writeFile(randomBytes(32));
      await handle.sync();
    } finally {
      await handle.close();
    }
  }
}

async function seedSupabase(supabase, environment) {
  const databaseUrl = requiredSupabase(supabase, "DB_URL");
  await run("psql", [databaseUrl, "-q", "-v", "ON_ERROR_STOP=1", "-f", "supabase/seed.sql"], {
    capture: true,
    sensitive: true,
    environment,
  });
  await run(
    "psql",
    [databaseUrl, "-q", "-v", "ON_ERROR_STOP=1", "-f", "supabase/development-seed.sql"],
    {
      capture: true,
      sensitive: true,
      environment: {
        ...environment,
        PGOPTIONS: "-c worldstream.development_seed=visible-local-only",
      },
    },
  );
  const verified = await run(
    "psql",
    [
      databaseUrl,
      "-At",
      "-v",
      "ON_ERROR_STOP=1",
      "-c",
      `select (select count(*) from platform_store.activity_listing_revisions where listing_revision_digest = '${LISTING_DIGEST}'), (select count(*) from platform_store.github_identities where auth_user_id = '${DEVELOPMENT_USER_ID}' and provider_subject = '${DEVELOPMENT_PROVIDER_SUBJECT}');`,
    ],
    { capture: true, sensitive: true, environment },
  );
  if (verified.stdout.trim() !== "1|1") throw new Error("local Supabase seed verification failed");
}

async function importClientDeclarations(ctl) {
  const declaration = join(REPOSITORY_ROOT, "config", "activity-clients", "cli-import.json");
  const preview = await ctl(["init", "--client-declaration", declaration, "--preview"], {
    capture: true,
  });
  let digest;
  try {
    digest = JSON.parse(preview.stdout).import_review.digest;
  } catch {
    throw new Error("worldstreamctl returned an invalid client import review");
  }
  if (typeof digest !== "string" || !/^blake3:[0-9a-f]{64}$/u.test(digest)) {
    throw new Error("worldstreamctl client import review omitted its exact digest");
  }
  await ctl(["init", "--client-declaration", declaration, "--approve-imports", digest]);
}

async function assertPortsAvailable(ports, reusableNames) {
  for (const [name, selected] of Object.entries(ports)) {
    if (reusableNames.has(name)) continue;
    await new Promise((resolvePromise, rejectPromise) => {
      const probe = createServer();
      probe.unref();
      probe.once("error", () => {
        rejectPromise(
          new Error(
            `${name} port ${selected} is already in use. Stop that process or configure an identity-safe alternate port.`,
          ),
        );
      });
      probe.listen(selected, "127.0.0.1", () => probe.close(resolvePromise));
    });
  }
}

async function compatibleAgentHeistAlreadyRunning(portNumber) {
  try {
    const response = await fetch(`http://127.0.0.1:${portNumber}/agent-heist/`, {
      signal: AbortSignal.timeout(1_000),
    });
    if (response.status !== 200) return false;
    const contentSecurityPolicy = response.headers.get("content-security-policy") ?? "";
    const body = await response.text();
    return (
      contentSecurityPolicy.includes("connect-src 'self' http://127.0.0.1:9420") &&
      body.includes("<title>Agent Heist · WorldStream Activity Client</title>")
    );
  } catch {
    return false;
  }
}

function ownedChild(name, command, args, environment, shuttingDown) {
  const child = spawn(command, args, {
    cwd: REPOSITORY_ROOT,
    env: environment,
    detached: process.platform !== "win32",
    stdio: ["ignore", "pipe", "pipe"],
  });
  const recent = [];
  for (const [stream, label] of [
    [child.stdout, "out"],
    [child.stderr, "err"],
  ]) {
    stream.setEncoding("utf8");
    stream.on("data", (value) => {
      for (const line of value.split(/\r?\n/u).filter(Boolean)) {
        recent.push(`${label}: ${line}`);
        if (recent.length > 20) recent.shift();
        process.stdout.write(`[${name}] ${line}\n`);
      }
    });
  }
  const failure = new Promise((_, rejectPromise) => {
    child.once("error", rejectPromise);
    child.once("exit", (code, signal) => {
      if (!shuttingDown()) {
        rejectPromise(
          new Error(
            `${name} exited before shutdown (${signal ?? code ?? "unknown"}).\n${recent.join("\n")}`,
          ),
        );
      }
    });
  });
  return { child, failure, name };
}

async function readiness(ports, ctl, children) {
  const checks = [
    waitForHttp("Platform BFF", `http://127.0.0.1:${ports.platform}/api/dev/status`, 200, children),
    waitForHttp("fake OpenRouter", `http://127.0.0.1:${ports.fakeOpenRouter}/healthz`, 200, children),
    waitForHttp("product", `http://127.0.0.1:${ports.product}/`, 200, children),
    waitForHttp("Agent Heist", `http://127.0.0.1:${ports.heist}/agent-heist/`, 200, children),
    waitForHttp("Hosted Gateway", `http://127.0.0.1:${ports.gateway}/readyz`, 200, children),
    waitForCommand(
      "Runtime and Controller",
      () => ctl(["server", "status"], { capture: true, quiet: true }),
      children,
    ),
  ];
  await Promise.race([Promise.all(checks), ...children.map(({ failure }) => failure)]);
}

async function waitForHttp(name, url, expectedStatus, children) {
  const deadline = Date.now() + READINESS_TIMEOUT_MS;
  while (Date.now() < deadline) {
    assertChildrenLive(children);
    try {
      const response = await fetch(url, { signal: AbortSignal.timeout(2_000) });
      if (response.status === expectedStatus) return;
    } catch {
      // The bounded retry loop owns the diagnostic.
    }
    await delay(250);
  }
  throw new Error(`${name} did not become ready within ${READINESS_TIMEOUT_MS / 1000} seconds`);
}

async function waitForCommand(name, check, children) {
  const deadline = Date.now() + READINESS_TIMEOUT_MS;
  while (Date.now() < deadline) {
    assertChildrenLive(children);
    try {
      await check();
      return;
    } catch {
      await delay(250);
    }
  }
  throw new Error(`${name} did not become ready within ${READINESS_TIMEOUT_MS / 1000} seconds`);
}

function assertChildrenLive(children) {
  for (const { child, name } of children) {
    if (child.exitCode !== null || child.signalCode !== null) {
      throw new Error(`${name} exited during readiness checks`);
    }
  }
}

async function verifyDevelopmentFlow(ports) {
  const productOrigin = `http://127.0.0.1:${ports.product}`;
  const signedIn = await fetch(`${productOrigin}/api/dev/sign-in`, {
    method: "POST",
    headers: { "content-type": "application/json", origin: productOrigin },
    body: JSON.stringify({ mode: DEVELOPMENT_MODE }),
  });
  if (signedIn.status !== 200) throw new Error("development identity sign-in check failed");
  const cookie = signedIn.headers.getSetCookie()[0]?.split(";", 1)[0];
  if (cookie === undefined) throw new Error("development identity cookie check failed");
  const session = await fetch(`${productOrigin}/api/auth/session`, { headers: { cookie } });
  if (session.status !== 200) throw new Error("development session round-trip check failed");

  const provider = await fetch(
    `http://127.0.0.1:${ports.fakeOpenRouter}/api/v1/chat/completions`,
    {
      method: "POST",
      headers: {
        authorization: `Bearer ${FAKE_OPENROUTER_KEY}`,
        "content-type": "application/json",
      },
      body: JSON.stringify({
        model: "worldstream/development-deterministic",
        messages: [{ role: "user", content: "readiness" }],
        max_tokens: 1,
      }),
    },
  );
  if (provider.status !== 200) throw new Error("fake OpenRouter contract check failed");

  const { encodeCanonical, taggedBlake3 } = await import(
    pathToFileURL(
      join(REPOSITORY_ROOT, "sdk", "typescript-pack", "packages", "pack-sdk", "dist", "index.js"),
    ).href
  );
  const [frozenLaunchRequest, frozenRoster, frozenRoomSetupSpecification] = await Promise.all(
    [
      "fixtures/hosted-contract/valid/agent-heist-launch-request.json",
      "fixtures/hosted-contract/valid/agent-heist-frozen-roster.json",
      "fixtures/hosted-contract/expected/agent-heist-room-setup.json",
    ].map(async (path) => JSON.parse(await readFile(join(REPOSITORY_ROOT, path), "utf8"))),
  );
  const launchBytes = encodeCanonical(frozenLaunchRequest);
  const rosterBytes = encodeCanonical(frozenRoster);
  const setupBytes = encodeCanonical(frozenRoomSetupSpecification);
  const launchRequest = {
    schema: "worldstream/hosted-launch-request/v1",
    listing_revision_digest: LISTING_DIGEST,
    launch_request_digest: taggedBlake3(launchBytes),
    launch_input_digest: taggedSha256(encodeCanonical(frozenLaunchRequest.inputs)),
    frozen_roster_digest: taggedSha256(rosterBytes),
    room_setup_specification_digest: taggedBlake3(setupBytes),
    room_setup_operation_id: "hosted-local-readiness",
    capacity_authorization: {
      schema: "worldstream/platform-capacity-authorization/v1",
      host_installation_id: HOST_INSTALLATION_ID,
      reservation_reference: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    },
    frozen_launch_request: frozenLaunchRequest,
    frozen_roster: frozenRoster,
    frozen_room_setup_specification: frozenRoomSetupSpecification,
  };
  const gateway = await fetch(`http://127.0.0.1:${ports.gateway}/v1/hosted/launch`, {
    method: "POST",
    headers: {
      authorization: `Bearer ${SERVICE_AUTHORITY}`,
      "content-type": "application/json",
    },
    body: encodeCanonical(launchRequest),
  });
  if (gateway.status !== 202) throw new Error("development Hosted Gateway contract check failed");
  const launchStatus = await gateway.json();
  if (
    launchStatus.schema !== "worldstream/hosted-launch-status/v1" ||
    launchStatus.room_setup_operation_id !== launchRequest.room_setup_operation_id
  ) {
    throw new Error("development Hosted Gateway returned invalid launch status");
  }
  const evidence = await fetch(`http://127.0.0.1:${ports.gateway}/v1/hosted/evidence`, {
    method: "POST",
    headers: {
      authorization: `Bearer ${SERVICE_AUTHORITY}`,
      "content-type": "application/json",
    },
    body: encodeCanonical({
      schema: "worldstream/hosted-launch-evidence-request/v1",
      listing_revision_digest: launchRequest.listing_revision_digest,
      launch_request_digest: launchRequest.launch_request_digest,
      room_setup_operation_id: launchRequest.room_setup_operation_id,
    }),
  });
  if (evidence.status !== 200) throw new Error("development Hosted Gateway evidence check failed");
  const evidenceStatus = await evidence.json();
  if (
    evidenceStatus.launch_request_digest !== launchStatus.launch_request_digest ||
    evidenceStatus.room_setup_operation_id !== launchStatus.room_setup_operation_id
  ) {
    throw new Error("development Hosted Gateway evidence identity changed");
  }
}

function taggedSha256(bytes) {
  return `sha256:${createHash("sha256").update(bytes).digest("hex")}`;
}

function printReady(ports, supabase) {
  process.stdout.write(
    [
      "",
      "WorldStream hosted development stack is ready.",
      `Product:        http://127.0.0.1:${ports.product}/`,
      `Agent Heist:    http://127.0.0.1:${ports.heist}/agent-heist/`,
      `Hosted Gateway: http://127.0.0.1:${ports.gateway}/`,
      `Supabase API:   ${requiredSupabase(supabase, "API_URL")}`,
      `Runtime:        127.0.0.1:${ports.runtime} (loopback only)`,
      `Controller:     127.0.0.1:${ports.controller} (loopback only)`,
      "",
      "Development substitutes are ACTIVE: identity bypass and fake OpenRouter.",
      "Press Ctrl-C to stop owned processes. Retained local data is preserved.",
      "",
    ].join("\n"),
  );
}

async function waitUntilStopped(children, beginShutdown) {
  const signal = new Promise((resolvePromise) => {
    const stop = (name) => {
      beginShutdown();
      resolvePromise(name);
    };
    process.once("SIGINT", () => stop("SIGINT"));
    process.once("SIGTERM", () => stop("SIGTERM"));
  });
  await Promise.race([signal, ...children.map(({ failure }) => failure)]);
}

async function stopChildren(children) {
  for (const { child } of [...children].reverse()) {
    if (child.exitCode !== null || child.signalCode !== null) continue;
    try {
      if (process.platform === "win32") child.kill("SIGTERM");
      else process.kill(-child.pid, "SIGTERM");
    } catch {
      // The child may have exited between observation and the signal.
    }
  }
  await Promise.all(
    children.map(async ({ child }) => {
      if (child.exitCode !== null || child.signalCode !== null) return;
      await Promise.race([once(child, "exit"), delay(5_000)]);
      if (child.exitCode === null && child.signalCode === null) {
        try {
          if (process.platform === "win32") child.kill("SIGKILL");
          else process.kill(-child.pid, "SIGKILL");
        } catch {
          // The bounded force-stop targets only a process group created above.
        }
      }
    }),
  );
}

async function succeeds(command, args, environment) {
  const result = await run(command, args, {
    allowFailure: true,
    capture: true,
    quiet: true,
    sensitive: true,
    environment: supabaseEnvironment(environment),
  });
  return result.code === 0;
}

async function run(command, args, options = {}) {
  const capture = options.capture === true || options.quiet === true;
  const child = spawn(command, args, {
    cwd: REPOSITORY_ROOT,
    env: options.environment ?? process.env,
    stdio: capture ? ["ignore", "pipe", "pipe"] : "inherit",
  });
  let stdout = "";
  let stderr = "";
  if (capture) {
    child.stdout.setEncoding("utf8");
    child.stderr.setEncoding("utf8");
    child.stdout.on("data", (value) => {
      stdout = boundedAppend(stdout, value);
    });
    child.stderr.on("data", (value) => {
      stderr = boundedAppend(stderr, value);
    });
  }
  const [code, signal] = await once(child, "exit");
  const result = { code: code ?? 1, signal, stdout, stderr };
  if (result.code !== 0 && options.allowFailure !== true) {
    const detail = options.sensitive === true ? "output redacted" : tail(stderr || stdout, 20);
    throw new Error(`${command} failed with status ${signal ?? result.code}: ${detail}`);
  }
  return result;
}

function boundedAppend(current, value) {
  const next = current + value;
  return next.length <= 1024 * 1024 ? next : next.slice(-1024 * 1024);
}

function tail(value, lines) {
  return value.trim().split(/\r?\n/u).slice(-lines).join("\n");
}

function parseEnvironmentOutput(value) {
  const result = {};
  for (const line of value.split(/\r?\n/u)) {
    const match = /^([A-Z][A-Z0-9_]*)=(.*)$/u.exec(line);
    if (match === null) continue;
    const [, name, raw] = match;
    if (name === undefined || raw === undefined) continue;
    result[name] = raw.startsWith('"') ? JSON.parse(raw) : raw;
  }
  return result;
}

function requiredSupabase(values, name) {
  const value = values[name];
  if (typeof value !== "string" || value.length === 0) {
    throw new Error(`Supabase status omitted ${name}`);
  }
  return value;
}

function supabaseEnvironment(environment) {
  return {
    ...environment,
    SUPABASE_AUTH_EXTERNAL_GITHUB_CLIENT_ID: "worldstream-hosted-local",
    SUPABASE_AUTH_EXTERNAL_GITHUB_SECRET: "worldstream-hosted-local-development-secret",
  };
}

function port(value, name) {
  if (!/^\d{1,5}$/u.test(value)) throw new Error(`${name} port is invalid`);
  const result = Number(value);
  if (!Number.isSafeInteger(result) || result < 1 || result > 65_535) {
    throw new Error(`${name} port is invalid`);
  }
  return result;
}

function delay(milliseconds) {
  return new Promise((resolvePromise) => setTimeout(resolvePromise, milliseconds));
}

if (process.argv[1] !== undefined && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  void main().catch((caught) => {
    const message = caught instanceof Error ? caught.message : "hosted development startup failed";
    process.stderr.write(`hosted:dev failed: ${message}\n`);
    process.exitCode = 1;
  });
}
