import assert from "node:assert/strict";
import { test } from "node:test";

import {
  assertHostedDevelopmentAllowed,
  hostedDevelopmentPorts,
  renderHostedDevelopmentConfig,
} from "./hosted-dev.mjs";

test("hosted development refuses production mode", () => {
  assert.throws(() => assertHostedDevelopmentAllowed({ NODE_ENV: "production" }));
  assert.throws(() => assertHostedDevelopmentAllowed({ VERCEL_ENV: "production" }));
  assert.doesNotThrow(() => assertHostedDevelopmentAllowed({ NODE_ENV: "development" }));
});

test("review-bound ports cannot drift silently", () => {
  assert.deepEqual(hostedDevelopmentPorts({}), {
    runtime: 9410,
    controller: 9420,
    gateway: 8080,
    product: 5180,
    heist: 5173,
    platform: 3000,
    fakeOpenRouter: 8787,
  });
  assert.throws(() => hostedDevelopmentPorts({ WORLDSTREAM_HOSTED_CONTROLLER_PORT: "9999" }));
  assert.throws(() => hostedDevelopmentPorts({ WORLDSTREAM_HOSTED_HEIST_PORT: "9998" }));
  assert.throws(() => hostedDevelopmentPorts({ WORLDSTREAM_HOSTED_PRODUCT_PORT: "5190" }));
  assert.throws(() =>
    hostedDevelopmentPorts({ WORLDSTREAM_HOSTED_PRODUCT_PORT: "8080" }),
  );
});

test("generated Runtime configuration retains dedicated absolute paths", () => {
  assert.equal(
    renderHostedDevelopmentConfig({
      dataDirectory: "/tmp/worldstream hosted/data",
      secretFile: "/tmp/worldstream hosted/authority.secret",
      runtimePort: 9410,
    }),
    `# Generated by pnpm hosted:dev. Retained local data is not deleted on shutdown.
config_version = 1

[server]
bind = "127.0.0.1:9410"

[storage]
profile = "sqlite-bundled"
data_dir = "/tmp/worldstream hosted/data"
deployment_lineage = "development/hosted-local"
storage_epoch = 1

[authority.bootstrap]
secret_file = "/tmp/worldstream hosted/authority.secret"
`,
  );
});
